repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0 # Use the latest version
    hooks:
      - id: flake8
  - repo: https://github.com/psf/black
    rev: 23.3.0 # Use the latest stable version
    hooks:
      - id: black
        language_version: python3